version: '3.4'

services:
  obscura:
    image: obscura
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./application:/app/application
    ports:
      - 8001:8001
    depends_on:
      - redis
  redis:
    image: "redis:latest"