version: '3.4'

services:
  obscura:
    image: obscura
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./application:/app/application
    ports:
      - 8001:8001
    depends_on:
      - redis
  worker:
    build: .
    command: flask rq worker high default
    environment:
      FLASK_APP: application:init_app
    depends_on:
      - redis
  redis:
    image: "redis:latest"